---
home: "{{ ansible_env.HOME }}"

nodejs_versions:
  - v4.2.1

nodejs_packages:
  - babel
  - bower
  - coffee-script
  - coffeelint
  - eslint
  - grunt-cli
  - gulp
  - html2jade
  - jade
  - jake
  - js-beautify
  - js-yaml
  - js2coffee
  - jsonlint
  - jspm
  - karma-cli
  - less
  - LiveScript
  - nesh
  - npm-check-updates
  - sloc
  - tern
  - yo
