---
- hosts: all
  vars:
    home: /Users/sigriston
    src_dir: /Users/sigriston/src
  tasks:
    - name: tap homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - railwaycat/emacsmacport
        - caskroom/fonts

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install macvim
      homebrew: name=macvim state=latest install_options=custom-icons,override-system-vim

    - name: install emacs
      homebrew: name=emacs-mac state=latest install_options=with-spacemacs-icon

    - name: install homebrew cask apps
      homebrew_cask: name={{ item }} state=present
      with_items:
        - adobe-photoshop-lightroom
        - clipmenu
        - controlplane
        - firefox
        - flux
        - google-chrome
        - google-drive
        - iterm2
        - java
        - julia
        - loading
        - macdown
        - microsoft-office
        - packer
        - r
        - rstudio
        - sequel-pro
        - skype
        - spectacle
        - transmission
        - vagrant
        - virtualbox
        - vlc
        - xmind

    - name: install fonts
      homebrew_cask: name={{ item }} state=present
      with_items:
        - font-lato
        - font-source-code-pro
        - font-source-sans-pro
        - font-source-serif-pro

    - name: get emacs-mac prefix
      command: brew --prefix emacs-mac
      register: emacs_mac_prefix

    - name: link Emacs.app under Applications
      file: path={{ home }}/Applications src={{ emacs_mac_prefix.stdout }}/Emacs.app state=link

    - name: install spacemacs
      git: repo=http://github.com/syl20bnr/spacemacs dest={{ home }}/.emacs.d

    - name: install ndenv
      git: repo=http://github.com/riywo/ndenv dest={{ home }}/.ndenv

    - name: install node-build
      git: repo=http://github.com/riywo/node-build dest={{ home }}/.ndenv/plugins/node-build