---
- name: install pip to system python
  easy_install: name=pip
  become: yes

- name: install pip packages to system python
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
  become: yes
  ignore_errors: yes
