---
- name: install pyenv
  homebrew: name="{{ item }}" state=latest
  with_items:
  - pyenv
  - pyenv-virtualenv
  - pyenv-which-ext

- name: install pip to system python
  easy_install: name=pip
  become: yes

- name: install python
  shell: "pyenv install {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ item }}"
  with_items: "{{ python_versions }}"

- name: install pip packages
  pip:
    name: "{{ item[1] }}"
    state: latest
    executable: "{{ ansible_env.HOME }}/.pyenv/versions/{{ item[0] }}/bin/pip"
  with_nested:
    - "{{ python_versions }}"
    - "{{ python_packages }}"
  ignore_errors: yes

- name: install pip packages to system python
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
  ignore_errors: yes