---
- name: add emacsmacport homebrew tap
  homebrew_tap: tap=railwaycat/emacsmacport state=present

- name: install emacs
  homebrew: name=emacs-mac state=latest install_options=with-spacemacs-icon

- name: link Emacs.app under Applications
  homebrew: name=emacs-mac state=linked

- name: link .spacemacs
  file: path="{{ home }}/.spacemacs" src="{{ src_dir }}/dotfiles/spacemacs/spacemacs" state=link

- name: install spacemacs
  git: repo=http://github.com/syl20bnr/spacemacs dest="{{ home }}/.emacs.d"