---
- name: restart affected apps
  shell: killall '"{{ item }}"' > /dev/null 2>&1
  become: yes
  ignore_errors: yes
  with_items:
    - Activity Monitor
    - Address Book
    - Calendar
    - Contacts
    - cfprefsd
    - Dock
    - Finder
    - Google Chrome
    - Google Chrome Canary
    - Mail
    - Messages
    - Opera
    - Safari
    - SizeUp
    - Spectacle
    - SystemUIServer
    - Transmission
    - Twitter
    - iCal
